# Generated by Django 4.1.7 on 2023-03-31 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecomapp', '0003_importingrecord_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('numstaffcreated', models.IntegerField(blank=True, db_column='NumStaffCreated', null=True)),
                ('numproductprocessed', models.IntegerField(blank=True, db_column='NumProductProcessed', null=True)),
                ('numbills', models.IntegerField(blank=True, db_column='NumBills', null=True)),
                ('numorderprocessed', models.IntegerField(blank=True, db_column='NumOrderProcessed', null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
                ('staffid', models.OneToOneField(db_column='StaffID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecomapp.staffs')),
            ],
            options={
                'db_table': 'manager',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='genreid',
        ),
        migrations.RemoveField(
            model_name='book',
            name='productid',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='productid',
        ),
        migrations.RemoveField(
            model_name='electronic',
            name='productid',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='town',
            new_name='subdistrict',
        ),
        migrations.RemoveField(
            model_name='product',
            name='expirydate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturingdate',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturingyear',
            field=models.IntegerField(blank=True, db_column='ManufacturingDate', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Clothes',
        ),
        migrations.DeleteModel(
            name='Electronic',
        ),
    ]
