# Generated by Django 4.1.7 on 2023-03-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_manager_remove_book_genreid_remove_book_productid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_create',
            field=models.DateField(blank=True, db_column='Date_created', null=True),
        ),
    ]
