# Generated by Django 4.1.7 on 2023-03-31 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_account_date_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
    ]
