# Generated by Django 4.1.7 on 2023-04-01 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0008_staffs_idstaff_alter_staffs_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='idStaff',
        ),
        migrations.AddField(
            model_name='staffs',
            name='codeStaff',
            field=models.CharField(db_column='codeStaff', default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffs',
            name='userid',
            field=models.OneToOneField(db_column='UsersID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecomapp.users'),
        ),
    ]
