# Generated by Django 4.1.7 on 2023-04-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0009_remove_staffs_idstaff_staffs_codestaff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturingyear',
            field=models.IntegerField(blank=True, db_column='ManufacturingYear', null=True),
        ),
    ]
