# Generated by Django 4.1.7 on 2023-04-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0011_alter_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False),
        ),
    ]
