# Generated by Django 4.1.7 on 2023-04-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0014_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='codeproduct',
            field=models.CharField(db_column='CodeStaff', default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False),
        ),
    ]
