# Generated by Django 4.1.7 on 2023-04-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0016_book_clothes_electronic_remove_banking_paymentid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='phonenumber_receive',
            new_name='phonenumberreceive',
        ),
        migrations.RemoveField(
            model_name='product',
            name='codeproduct',
        ),
    ]
