# Generated by Django 4.1.7 on 2023-04-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0017_rename_phonenumber_receive_shippingaddress_phonenumberreceive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='addressid',
        ),
    ]
