# Generated by Django 4.1.7 on 2023-04-12 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0019_alter_customershippingaddress_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customershippingaddress',
            name='id',
            field=models.AutoField(db_column='ID', default=5, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='customerid',
            field=models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, to='ecomapp.customer'),
        ),
    ]
