# Generated by Django 4.1.7 on 2023-05-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0020_customershippingaddress_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(blank=True, db_column='Price', null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='salary',
            field=models.IntegerField(blank=True, db_column='Salary', null=True),
        ),
    ]
