# Generated by Django 4.1.7 on 2023-05-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0021_alter_item_price_alter_staffs_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_import',
            field=models.IntegerField(blank=True, db_column='Price_import', null=True),
        ),
    ]
