from django.contrib import admin
from .models import *


admin.site.register(
    [Account,
    Address,
    Book,
    Businessstaff,
    Cartline,
    Category,
    Clothes,
    Contactinfo,
    Customer,
    CustomerShippingaddress,
    Customerreview,
    Electronic,
    Feedback,
    Fullname,
    Historyline,
    Importingrecord,
    Item,
    Manager,
    Order,
    Orderhistory,
    Orderitem,
    Payment,
    Producer,
    Product,
    ProductCategory,
    Reviewreply,
    Salesstaff,
    Shippingaddress,
    Shoppingcart,
    Staffs,
    Supplier,
    Users,
    Warehousestaff,
    Wishlist,
    Wishlistline])
